# Generated by Django 2.2.3 on 2019-07-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30)),
                ('blog', models.TextField(max_length=2000)),
                ('title', models.CharField(max_length=50)),
                ('Science', models.BooleanField()),
                ('Math', models.BooleanField()),
                ('History', models.BooleanField()),
                ('Programming', models.BooleanField()),
                ('cs', models.BooleanField()),
                ('cpp', models.BooleanField()),
                ('ml', models.BooleanField()),
                ('iot', models.BooleanField()),
                ('Robots', models.BooleanField()),
                ('Space', models.BooleanField()),
                ('Literature', models.BooleanField()),
                ('appD', models.BooleanField()),
                ('Political', models.BooleanField()),
                ('Sports', models.BooleanField()),
                ('Cricket', models.BooleanField()),
                ('Bollywood', models.BooleanField()),
                ('Hollywood', models.BooleanField()),
                ('TV', models.BooleanField()),
                ('Life', models.BooleanField()),
                ('public', models.BooleanField()),
                ('private', models.BooleanField()),
            ],
        ),
    ]
